# Generated by Django 4.2.24 on 2025-09-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('contract_address', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_low', models.FloatField(default=500)),
                ('threshold_mid', models.FloatField(default=1000)),
                ('threshold_high', models.FloatField(default=1500)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watcher.token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watcher.user')),
            ],
        ),
    ]
