# Generated by Django 4.2.24 on 2025-09-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='name',
        ),
        migrations.RemoveField(
            model_name='token',
            name='symbol',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='last_alert_level',
            field=models.CharField(choices=[('none', 'none'), ('low', 'low'), ('mid', 'mid'), ('high', 'high')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='usertoken',
            name='last_seen_mcap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='contract_address',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='usertoken',
            unique_together={('user', 'token')},
        ),
    ]
